### ISSUE TITLE
Make dependency more-itertools less strict

### ISSUE THREAD

**Issue by mghh** [danields761/class-doc#1]
Hi,

I would like to use class-doc in my project but the version dependency on more-itertools in pyproject.toml
is to strict in my case. Could you change `more-itertools = "^7.2"` into this:

```
[tool.poetry.dependencies]
python = "^3.6"
more-itertools = ">=7.2"
```
Kind regards,
Martin

**Comment by danields761** [comment]
Hello,

Thank you for pointing out this issue! 

I fixed it already and pushed on pypi.org under version 0.2.6. Could you, please, check that new version solves the issue?

**Comment by mghh** [comment]
Hi,

class-doc is now fine for me :)

But now I run into trouble with pydantic_settings-0.2.5 which pinned class-doc to 0.2.0b.

In our UseCase it will make more sense to use class-doc in custom code for documentation of multiple merged pydantic.BaseSettings instead of pydantic_settings.attrs_docs.apply_attributes_docs.

Thanks a lot for fixing the problem.
